arch: ppc64le


sudo: required
services:
  - docker

script:
  - docker run -a stdin -a stdout -a stderr -u root ubuntu:18.04 bash -c 'apt update -y && apt install -y git'
  - docker run -it ubuntu:18.04 bash -c 'apt update -y && apt install -y git'
