arch: 
  - ppc64le
sudo: required
services:
  - docker

script:
  - sudo apt install cmake
  - docker run -t ubuntu:18.04 bash -c 'apt update -y && apt install -y cmake'
  - docker run -t centos:7 bash  -c 'yum update -y && yum install -y cmake'

